CLASSROOM_TEMPLATES = [  
    "a photo of a person in a classroom who is {}.",
    "a bad photo of a person in a classroom who is {}.",
    "a photo of many people in a classroom who are {}.",
    "a low resolution photo of a person in a classroom who is {}.",
    "a rendering of a person in a classroom who is {}.",
    "a photo of a hard to see person in a classroom who is {}.",
    "a bright photo of a person in a classroom who is {}.",
    "a photo of a clean classroom where a person is {}.",
    "a photo of a dirty classroom where a person is {}.",
    "a dark photo of a person in a classroom who is {}.",
    "a drawing of a person in a classroom who is {}.",
    "a photo of my classroom where a person is {}.",
    "a photo of the cool classroom where a person is {}.",
    "a close-up photo of a person in a classroom who is {}.",
    "a black and white photo of a person in a classroom who is {}.",
    "a painting of a classroom scene where a person is {}.",
    "a pixelated photo of a person in a classroom who is {}.",
    "a bright photo of a classroom where a person is {}.",
    "a cropped photo of a person in a classroom who is {}.",
    "a photo of the dirty classroom where a person is {}.",
    "a jpeg corrupted photo of a person in a classroom who is {}.",
    "a blurry photo of a person in a classroom who is {}.",
    "a good photo of a person in a classroom who is {}.",
    "a photo of one person in a classroom who is {}.",
    "a close-up photo of the person in a classroom who is {}.",
    "a low resolution photo of a person in a classroom who is {}.",
    "a photo of the clean classroom where a person is {}.",
    "a photo of a large classroom where a person is {}.",
    "a photo of a nice classroom where a person is {}.",
    "a photo of a weird classroom where a person is {}.",
    "a blurry photo of a classroom where a person is {}.",
    "a cartoon of a classroom scene where a person is {}.",
    "art of a classroom scene where a person is {}.",
    "a sketch of a classroom scene where a person is {}.",
    "a pixelated photo of a classroom where a person is {}.",
]
